name 'docker'
maintainer 'alexander harlass'
maintainer_email 'mail@alexander-harlass.de'
license 'all_rights'
description 'Installs/Configures docker'
long_description 'Installs/Configures docker'
version '0.1.0'
